### PR TITLE
Typos, add LuckPerms and EssentialsX, other fixes

### PR DESCRIPTION
**Pull request by BrightSkyz**
Fixed some typos, added LuckPerms and EssentialsX to the supported plugins, added links to some more plugins, updated license year, and some other small changes.

### CODE REVIEW

**Comment by BrightSkyz** [comment]
Also, the checks that failed are unrelated to my pull request. You can merge mine with no problems. The failed checks are caused by other parts of the code that don't interact with the things I did.

**Comment by DoNotSpamPls** [comment]
Minor complaint - the license year should be 2011-2018, indicating the project started in 2011

**Comment by BrightSkyz** [comment]
@DoNotSpamPls I have fixed the license starting year, the URLs are not just hyperlinks on the names is because it's much easier for people to tell what website they are going to and because that's the way it was before I created the pull request.

**Comment by TheIntelloBox** [comment]
Merge it please

**Pull request merged**
