### PR TITLE
Updated OverPermissions support to v2.0.0

### PR DESCRIPTION
**Pull request by OverCaste**
I had all of this done a long time ago, but only now got around to making the vault modules.

Mostly properly tested, tell me if anything needs to be changed.

### CODE REVIEW

**Comment by Sleaker** [comment]
So a couple things. Don't remove license headers. Don't remove the Chat_ name component on the getName for the Chat interface. It's there on purpose.  Make sure you're versioning the updated jar file in the pom and in the filename to prevent confusion. Vault doesn't use * imports.  You changed the style of a lot of the code to have { on their own line.  This goes against the code styling I have in here. Minor annoyance but I like to keep it consistent.

**Comment by OverCaste** [comment]
Forgot the chat_ thing, one moment

**Comment by OverCaste** [comment]
Another little problem-- I'll push the (hopefully final) commit today.

**Comment by Sleaker** [comment]
closing: abandoned. Feel free to re-open when it's compiling properly and follows the guidelines I posted above.

**Comment by OverCaste** [comment]
Is the only thing missing the Chat_ prefix? I'm afraid I missed that the first time around, thought you had forgotten about this PR.

**Comment by OverCaste** [comment]
Actually, it doesn't seem to be a prefix at all?  The getName() function is functionally unchanged, besides a single inlined static field?

public String getName( ) {
      return "OverPermissions_Chat";
     }

versus

private static final String name = "OverPermissions_Chat";
    @Override
    public String getName() {
        return name;
    }

**Comment by Sleaker** [comment]
oh my fault, it's probably a dependency download issue.

**Comment by OverCaste** [comment]
It looks like the krinsoft.net:8085 server is down, so that dependency can't be resolved anymore.
I have a local backup of the jar if you need it, from previous vault builds.

Other than that, I can confirm that it at least builds with this PR, and the aformentioned cached jar for the missing dependenc(ies).

**Comment by OverCaste** [comment]
Any updates regarding this PR?

**Comment by Sleaker** [comment]
merged. I need to fix the dependency issues still. Thanks for the work.

**Pull request merged**
