### PR TITLE
Specialize EssentialsX economy to support UUID based lookup

### PR DESCRIPTION
**Pull request by RickyB98**
This pull request continues to support the normal Essentials plugin, as well as support the UUID based lookup implemented in EssentialsX. This avoids redundant name to UUID resolutions in case the developer uses the methods with `OfflinePlayer`. Backwards compatibility is preserved for plugins using the `String` methods. Uses latest EssentialsX.

### CODE REVIEW

**Comment by RickyB98** [comment]
Looks like the Travis check fails due to a failed deploy, although that shouldn't happen since it's a pull request. I'll leave that to someone else.

**Comment by Sleaker** [comment]
This is a great candidate and time for EssentialsX to start handling and maintaining it's own hook in it's own source tree.

**Comment by RickyB98** [comment]
And why would EssentialsX be different from all the other plugins whose hooks you do maintain in this source tree?

**Comment by Sleaker** [comment]
@RickyB98 I no longer maintain hooks or add new hooks in Vault. the remaining ones are for legacy purposes only. I also never added an EssentialsX plugin connector.

**Pull request closed without merging**
