### PR TITLE
Finish removal of native support for abandoned economy plugins.

### PR DESCRIPTION
**Pull request by LlmDl**
- All economy plugins removed as libs.
  - None of them are actively developed, many abandoned since 2015 or earlier.
- Removal of Register hook.
  - Register was last updated by the Towny team, many years ago, it is no longer used by any modern server.

This Pull Request complements https://github.com/MilkBowl/VaultAPI/pull/112 in finishing the removal of economy plugins from Vault. This process was begun years ago when many other such economy plugins were removed after being determined abandoned. 

The modern standard is that an economy plugin will implement Vault in their own code.

Here are the last-update dates on the plugins removed:
Capture

### CODE REVIEW

**Comment by LlmDl** [comment]
Took me a few tries to get this building properly, locally it complains about the pom formatting but it is building now as best it can. CI only failed to deploy after building correctly.

**Comment by mirolm** [comment]
Agree on that - Essentials currently has code to load Vault properly. It will be good to let go of the old economy code.

P.S. Maybe the same can be done with the old permission plugins code...

**Comment by cerealcable** [comment]
This PR has failed checks (we've sinced fixed the build configs, so rebase) and has conflicts. Any chance @LlmDl you could address this and then we'll be able to get to final reviews/merging?

**Comment by Jack1424** [comment]
You should remove these plugins from the README as well

**Comment by LlmDl** [comment]
First PR to build in a decade! /s

**Review by cerealcable — APPROVED** [review]
Looks good, time to move on!

**Comment by LlmDl** [comment]
Just back from holiday and I see this is merged, very nice! I'll start work on your Vault-API review tomorrow.

**Pull request merged**
