### PR TITLE
Update to use Static Getter for BukkitPermissions in GroupManager. 

### PR DESCRIPTION
**Pull request by ElgarL**
The Static field BukkitPermissions will be changing to private and
accessed via a getter in the future. This update allows for that change
while retaining backward compatibility with older/other builds of
GroupManager.

### CODE REVIEW

**Comment by ElgarL** [comment]
Builds and runs fine. no idea why your Jenkins is failing.

**Comment by Sleaker** [comment]
So I know there's a lot of work in what you're doing, my suggestion as I've told others is to move the Vault connector into your own codebase and just change the package it's in that way the old vault connector no longer detects or attempts to inject itself into the bukkit services. That way you can 100% manage the connector and any changes that need to happen for maintainability yourself.

**Comment by ElgarL** [comment]
Changing the package of the API isn't really feasible as some plug-ins hook GM directly and it would break compatibility.

**Comment by Sleaker** [comment]
Sorry, I'm keeping my stance on this one. I no longer provide functional API changeovers due to API breakages in supported plugins that are trying to adjust how their API is used.  If you want to adjust the API you'll need to conform to how I treat all plugins: manage and update your own implementation of the permission API class, or leave the access unchanged.

**Pull request closed without merging**
